import {useRef,useState} from 'react';
import {AlertTriangle, ArrowUpRight, CheckCircle2, ChevronDown, Clipboard, FileSearch, Globe2, Inbox, LockKeyhole, Mail, Paperclip, Radar, ShieldCheck, Upload, XCircle} from 'lucide-react';

type Analysis=any;
const cx=(...c:string[])=>c.filter(Boolean).join(' ');
const severity=(s:string)=>s==='CRITICAL'||s==='HIGH'?'danger':s==='MEDIUM'?'warning':'info';
function Badge({children,type}:{children:any,type?:string}){return <span className={cx('badge',type||'neutral')}>{children}</span>}
function Card({title,children,action, className=''}:{title?:string,children:any,action?:any,className?:string}){return <section className={cx('card',className)}>{title&&<div className="card-head"><h3>{title}</h3>{action}</div>}{children}</section>}
function Meter({value,max=100}:{value:number,max?:number}){return <div className="meter"><i style={{width:`${Math.min(100,value/max*100)}%`}}/></div>}

function Uploader({onAnalyze,loading}:{onAnalyze:(f:File)=>void,loading:boolean}){
 const [file,setFile]=useState<File|null>(null); const input=useRef<HTMLInputElement>(null);
 const pick=(f?:File)=>{if(f&&f.name.toLowerCase().endsWith('.eml'))setFile(f)};
 return <div className="upload-wrap"><div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pick(e.dataTransfer.files[0])}} onClick={()=>input.current?.click()}><input ref={input} type="file" accept=".eml" hidden onChange={e=>pick(e.target.files?.[0])}/><span className="upload-icon"><Upload/></span><h3>{file?file.name:'Drop your email sample here'}</h3><p>{file?`${(file.size/1024).toFixed(1)} KB · Ready for analysis`:'Drag & drop an .eml file, or browse from your device'}</p><button className="ghost" type="button">Choose .EML file</button></div>{file&&<button className="analyze" onClick={()=>onAnalyze(file)} disabled={loading}>{loading?'Running forensic analysis…':'Analyze Email'} <ArrowUpRight size={18}/></button>}<p className="privacy"><LockKeyhole size={14}/> Your email sample is analyzed securely and is not retained after analysis.</p></div>
}
function Overview({a}:{a:Analysis}){ const danger=a.classification==='PHISHING'||a.classification==='MALICIOUS';return <><Card className="verdict"><div><div className="eyebrow">EMAIL SECURITY VERDICT</div><h1>{a.classification}</h1><p>{a.verdict_explanation}</p><div className="category"><span>MESSAGE CATEGORY</span><b>{a.message_category.label}</b><small>{a.message_category.note}</small></div>{a.categories?.length ? <div className="category"><span>SECONDARY CLASSIFICATIONS</span><div style={{display:'flex',gap:'0.5rem',flexWrap:'wrap',marginTop:'0.5rem'}}>{a.categories.map((tag:string)=><Badge key={tag} type={tag.includes('PHISH')||tag.includes('MALWARE')?'danger':'warning'}>{tag.replace(/_/g,' ')}</Badge>)}</div></div> : null}<button className="text-btn"><Clipboard size={14}/> Copy investigation summary</button></div><div className={cx('score-ring',danger?'red':'amber')}><strong>{a.risk_score}</strong><span>/ 100</span><small>{a.risk_level} risk</small><small style={{display:'block',marginTop:'0.35rem'}}>Confidence: {Math.round((a.confidence ?? 0.5) * 100)}%</small></div></Card><div className="stats"><Stat icon={<Mail/>} label="Sender" value={a.email_metadata.sender}/><Stat icon={<Inbox/>} label="Recipient" value={a.email_metadata.recipient}/><Stat icon={<Globe2/>} label="Sending IP" value={a.email_metadata.sending_ip}/><Stat icon={<Paperclip/>} label="Indicators" value={`${a.findings.filter((f:any)=>f.severity!=='INFO').length} risk signals`}/></div></>}
function MailFlow({a}:{a:Analysis}){const hops=a.received_chain||[];const nodes=[{kind:'Sender',host:a.email_metadata.sender,detail:a.email_metadata.sender_domain},...hops.map((h:any)=>({kind:`Hop ${h.hop}`,host:h.to_host,detail:[h.ip,h.protocol,h.tls?'TLS':''].filter(Boolean).join(' · ')||'SMTP relay'})),{kind:'Recipient',host:a.email_metadata.recipient,detail:'Mailbox destination'}];return <Card title="Mail Flow" action={<span className="muted">Reconstructed from Received headers</span>}><div className="flow"><div className="flow-line"/>{nodes.map((node:any,i:number)=><div className="flow-node" key={`${node.kind}-${i}`}><span className={i===0?'origin':i===nodes.length-1?'destination':''}>{i===0?<Mail size={16}/>:i===nodes.length-1?<Inbox size={16}/>:<Globe2 size={16}/>}</span><div><small>{node.kind}</small><b title={node.host}>{node.host}</b><p>{node.detail}</p>{i>0&&i<nodes.length-1&&hops[i-1]?.timestamp&&<time>{hops[i-1].timestamp}</time>}</div></div>)}</div>{hops.length===0&&<div className="flow-note">No Received headers were available. The sender-to-recipient path cannot be independently reconstructed.</div>}<details className="hop-details"><summary>Inspect {hops.length} raw transport hop{hops.length===1?'':'s'}</summary>{hops.map((h:any)=><div key={h.hop}><b>Hop {h.hop}</b><span>{h.raw}</span></div>)}</details></Card>}
function Stat({icon,label,value}:{icon:any,label:string,value:string}){return <div className="stat"><span>{icon}</span><div><small>{label}</small><b title={value}>{value}</b></div></div>}
function Findings({items}:{items:any[]}){return <Card title="Key Findings" action={<Badge type="neutral">{items.length} signals</Badge>}><div className="findings">{items.length?items.map((x,i)=><div className="finding" key={i}><span className={cx('severity',severity(x.severity))}>{x.severity}</span><div><b>{x.title}</b><p>{x.description}</p><small><em>Evidence</em> {x.evidence}</small></div></div>):<div className="empty"><CheckCircle2/> No suspicious signals detected in local analysis.</div>}</div></Card>}
function Authentication({a}:{a:Analysis}){return <Card title="Authentication" action={<span className="muted">Parsed from message headers</span>}><div className="auth-grid">{Object.entries(a.authentication).map(([key,v]:any)=><div className="auth" key={key}><span>{key.toUpperCase()}</span><Badge type={v.status==='PASS'?'success':v.status==='FAIL'?'danger':'neutral'}>{v.status}</Badge><p>{v.signing_domain||v.record||v.policy||'No authentication chain found'}</p></div>)}</div></Card>}
function Scorecard({items}:{items:any[]}){return <Card title="Explainable Risk Score"><div className="scores">{items.map((x:any)=><div className="score-line" key={x.category}><div><b>{x.category}</b><span>{x.score}/{x.max_score}</span></div><Meter value={x.score} max={x.max_score}/></div>)}</div><p className="hint">Each category is capped to prevent a single indicator from being counted multiple times.</p></Card>}
function Table({title,items,kind}:{title:string,items:any[],kind:'urls'|'attachments'|'domains'|'ips'}){const empty=`No ${title.toLowerCase()} found.`; return <Card title={title} action={<Badge type="neutral">{items.length}</Badge>}>{!items.length?<div className="empty">{empty}</div>:<div className="table-scroll"><table><thead><tr>{kind==='urls'?<><th>URL / host</th><th>Signals</th><th>Risk</th></>:kind==='attachments'?<><th>Attachment</th><th>Type / size</th><th>SHA-256</th><th>Risk</th></>:<><th>{kind==='ips'?'IP address':'Domain'}</th><th>Role</th><th>Intelligence</th></>}</tr></thead><tbody>{items.map((x:any,i:number)=><tr key={i}>{kind==='urls'?<><td><b>{x.host}</b><small>{x.original}</small></td><td>{x.signals.length?x.signals.map((s:string)=><Badge key={s} type="warning">{s}</Badge>):'—'}</td><td><b>{x.risk_score}/100</b></td></>:kind==='attachments'?<><td><b>{x.name}</b><small>{x.signals.join(' · ')||'No local warning'}</small></td><td>{x.mime_type}<small>{x.size.toLocaleString()} bytes</small></td><td className="hash">{x.sha256}</td><td><b>{x.risk_score}/100</b></td></>:<><td><b>{kind==='ips'?x.ip:x.domain}</b></td><td>{x.role||'Observed'}</td><td>{x.reputation}</td></>}</tr>)}</tbody></table></div>}</Card>}
function Details({a}:{a:Analysis}){const [open,setOpen]=useState(false); return <><Card title="Sender & Message"><div className="details">{Object.entries(a.email_metadata).filter(([k])=>!['filename','size','url_count','attachment_count'].includes(k)).map(([k,v])=><div key={k}><small>{k.replaceAll('_',' ')}</small><b>{String(v)}</b></div>)}</div></Card><Card title="Content & Social Engineering"><div className="pills">{a.content_analysis.social_engineering_indicators.length?a.content_analysis.social_engineering_indicators.map((x:string)=><Badge type="warning" key={x}>{x}</Badge>):<span className="muted">No social-engineering patterns detected.</span>}</div><div className="preview">{a.content_analysis.preview_text||'No readable plain-text body available.'}</div></Card><Card title="Headers" action={<button className="text-btn" onClick={()=>setOpen(!open)}>Show Raw Headers <ChevronDown size={15}/></button>}>{open&&<pre>{a.raw_headers}</pre>}<div className="header-list">{a.headers.slice(0,8).map((h:any,i:number)=><div key={i}><b>{h.name}</b><span>{h.value}</span></div>)}</div></Card><Card title="Investigation Timeline"><div className="timeline">{a.timeline.map((t:any,i:number)=><div key={i}><time>{t.time}</time><i/><span>{t.event}</span></div>)}</div></Card></>}
function Report({a,onReset}:{a:Analysis,onReset:()=>void}){return <main className="analysis"><div className="topline"><button className="back" onClick={onReset}>← New analysis</button><div><Badge type="neutral"><Radar size={13}/> Ephemeral session</Badge><Badge type="neutral">ID {a.id.slice(0,8)}</Badge></div></div><Overview a={a}/><MailFlow a={a}/><div className="layout"><div className="primary"><Findings items={a.findings}/><Authentication a={a}/><Table title="URL Analysis" items={a.urls} kind="urls"/><Table title="Attachment Analysis" items={a.attachments} kind="attachments"/><Details a={a}/></div><aside><Scorecard items={a.score_breakdown}/><Table title="Domain Intelligence" items={a.domains} kind="domains"/><Table title="IP Intelligence" items={a.ips} kind="ips"/><Card title="Recommendations"><ol className="recommend">{a.recommendations.map((r:string,i:number)=><li key={i}>{r}</li>)}</ol></Card></aside></div></main>}
function App(){const [analysis,setAnalysis]=useState<Analysis>(); const [loading,setLoading]=useState(false);const [error,setError]=useState(''); async function run(file:File){setLoading(true);setError('');try{let form=new FormData();form.append('file',file);const r=await fetch('/api/analyze',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Analysis failed');setAnalysis(data)}catch(e:any){setError(e.message)}finally{setLoading(false)}}return <><header><div className="brand"><span><ShieldCheck/></span><b>Mail<span>Forensics</span></b></div><nav><a className="active">Analyze</a><a>Architecture</a><a>Privacy</a></nav><Badge type="success"><i className="dot"/> System operational</Badge></header>{analysis?<Report a={analysis} onReset={()=>setAnalysis(undefined)}/>:<main className="home"><div className="hero-label"><Radar size={15}/> EMAIL THREAT INVESTIGATION</div><h1>Analyze Any Email.<br/><em>Understand Every Signal.</em></h1><p>Upload an .eml sample and perform deep email forensics, authentication analysis, threat intelligence, phishing detection, and infrastructure investigation.</p><Uploader onAnalyze={run} loading={loading}/>{error&&<div className="error"><XCircle/> {error}</div>}<div className="feature-row"><span><FileSearch/> Full MIME analysis</span><span><ShieldCheck/> Explainable scoring</span><span><LockKeyhole/> Privacy-first processing</span></div></main>}<footer>MAILFORENSICS <span>•</span> Built for security investigation <span>•</span> Content is never retained by default</footer></>}
export default App;
